<template>

	<div>
		<div class="loadingio-spinner-spinner-gxgce9qe9x"><div class="ldio-d1zmzp57e4u">
		<div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
		</div></div>
	</div>

</template>

<style scoped>
@keyframes ldio-d1zmzp57e4u {
  0% { opacity: 1 }
  100% { opacity: .07 }
}
.ldio-d1zmzp57e4u div {
  left: 147.725px;
  top: 29.544999999999998px;
  position: absolute;
  animation: ldio-d1zmzp57e4u linear 1s infinite;
  background: #fff;
  width: 15px;
  height: 53px;
  border-radius: 0px / 0px;
  transform-origin: 7.7749999999999995px 150px;
}.ldio-d1zmzp57e4u div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9444444444444444s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(2) {
  transform: rotate(20deg);
  animation-delay: -0.8888888888888888s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(3) {
  transform: rotate(40deg);
  animation-delay: -0.8333333333333334s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(4) {
  transform: rotate(60deg);
  animation-delay: -0.7777777777777778s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(5) {
  transform: rotate(80deg);
  animation-delay: -0.7222222222222222s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(6) {
  transform: rotate(100deg);
  animation-delay: -0.6666666666666666s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(7) {
  transform: rotate(120deg);
  animation-delay: -0.6111111111111112s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(8) {
  transform: rotate(140deg);
  animation-delay: -0.5555555555555556s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(9) {
  transform: rotate(160deg);
  animation-delay: -0.5s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(10) {
  transform: rotate(180deg);
  animation-delay: -0.4444444444444444s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(11) {
  transform: rotate(200deg);
  animation-delay: -0.3888888888888889s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(12) {
  transform: rotate(220deg);
  animation-delay: -0.3333333333333333s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(13) {
  transform: rotate(240deg);
  animation-delay: -0.2777777777777778s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(14) {
  transform: rotate(260deg);
  animation-delay: -0.2222222222222222s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(15) {
  transform: rotate(280deg);
  animation-delay: -0.16666666666666666s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(16) {
  transform: rotate(300deg);
  animation-delay: -0.1111111111111111s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(17) {
  transform: rotate(320deg);
  animation-delay: -0.05555555555555555s;
  background: #fff;
}.ldio-d1zmzp57e4u div:nth-child(18) {
  transform: rotate(340deg);
  animation-delay: 0s;
  background: #fff;
}
.loadingio-spinner-spinner-gxgce9qe9x {
  width: 316px;
  height: 355px;
  display: inline-block;
  overflow: hidden;
}
.ldio-d1zmzp57e4u {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-d1zmzp57e4u div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>